sudo: require
services:
  - docker

before_install:
  - docker build -t chrismat/react-test -f ./react-client/Dockerfile.dev ./react-client

script:
  - docker run chrismat/react-test npm test -- --coverage

after_success:
  - docker build -t chrismat/multi-react-client ./react-client
  - docker build -t chrismat/multi-nginx ./nginx
  - docker build -t chrismat/multi-server ./server
  - docker build -t chrismat/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push the to the docker hub
  - docker push chrismat/multi-react-client
  - docker push chrismat/multi-nginx
  - docker push chrismat/multi-server
  - docker push chrismat/multi-worker